//! 合成数据集「青空日记」：仅供界面开发，全部为人造素材名、场景、镜次与时间码，
//! 不读取、不上传任何真实 XML/CSV。

use double_love_engine::{Diagnostic, DiagnosticLevel, OperationCounts};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ClipStatus {
    Processed,
    Ignored,
    Skipped,
    Failed,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Rating {
    Ok,
    Keep,
    Ng,
    None,
}

impl Rating {
    pub fn label(self) -> &'static str {
        match self {
            Rating::Ok => "ok",
            Rating::Keep => "kp",
            Rating::Ng => "ng",
            Rating::None => "—",
        }
    }
}

#[derive(Debug, Clone)]
pub struct FixtureClip {
    pub id: &'static str,
    pub new_name: &'static str,
    pub source_name: &'static str,
    pub scene: &'static str,
    pub shot: &'static str,
    pub take: &'static str,
    pub camera: &'static str,
    pub rating: Rating,
    pub tc_in: &'static str,
    pub duration: &'static str,
    pub from_csv: bool,
    pub status: ClipStatus,
    pub note: &'static str,
}

#[derive(Debug, Clone)]
pub struct RevisionEntry {
    pub revision: u64,
    pub operation: &'static str,
    pub committed_at: &'static str,
    pub summary: &'static str,
}

pub struct FixtureSet {
    pub project_name: &'static str,
    pub episode_label: &'static str,
    pub clips: Vec<FixtureClip>,
    pub diagnostics: Vec<Diagnostic>,
    pub revisions: Vec<RevisionEntry>,
    pub counts: OperationCounts,
    pub csv_unmatched: u64,
    pub export_blocked: bool,
}

pub fn aozora_diary() -> FixtureSet {
    let clips = vec![
        FixtureClip {
            id: "c01",
            new_name: "02_015_01_01a",
            source_name: "A003C001_260112DJ",
            scene: "015",
            shot: "01",
            take: "01",
            camera: "a",
            rating: Rating::Ok,
            tc_in: "01:00:03:12",
            duration: "00:00:11:08",
            from_csv: true,
            status: ClipStatus::Processed,
            note: "",
        },
        FixtureClip {
            id: "c02",
            new_name: "02_015_01_02a",
            source_name: "A003C002_260112DJ",
            scene: "015",
            shot: "01",
            take: "02",
            camera: "a",
            rating: Rating::Ng,
            tc_in: "01:00:19:04",
            duration: "00:00:08:16",
            from_csv: true,
            status: ClipStatus::Processed,
            note: "",
        },
        FixtureClip {
            id: "c03",
            new_name: "02_015_02_01b",
            source_name: "B001C003_260112DJ",
            scene: "015",
            shot: "02",
            take: "01",
            camera: "b",
            rating: Rating::Keep,
            tc_in: "01:00:41:20",
            duration: "00:00:14:02",
            from_csv: true,
            status: ClipStatus::Processed,
            note: "",
        },
        FixtureClip {
            id: "c04",
            new_name: "02_016_01_01a",
            source_name: "A003C004_260112DJ",
            scene: "016",
            shot: "01",
            take: "01",
            camera: "a",
            rating: Rating::Ok,
            tc_in: "01:01:02:10",
            duration: "00:00:09:21",
            from_csv: true,
            status: ClipStatus::Processed,
            note: "",
        },
        FixtureClip {
            id: "c05",
            new_name: "02_016_01_02b",
            source_name: "B001C005_260112DJ",
            scene: "016",
            shot: "01",
            take: "02",
            camera: "b",
            rating: Rating::None,
            tc_in: "01:01:18:00",
            duration: "00:00:12:13",
            from_csv: true,
            status: ClipStatus::Processed,
            note: "CSV 无评分",
        },
        FixtureClip {
            id: "c06",
            new_name: "02_016_03_01a",
            source_name: "A004C006_260112DJ",
            scene: "016",
            shot: "03",
            take: "01",
            camera: "a",
            rating: Rating::Ok,
            tc_in: "01:01:47:05",
            duration: "00:00:18:09",
            from_csv: true,
            status: ClipStatus::Processed,
            note: "",
        },
        FixtureClip {
            id: "c07",
            new_name: "02_017_01_01a",
            source_name: "A004C007_260112DJ",
            scene: "017",
            shot: "01",
            take: "01",
            camera: "a",
            rating: Rating::Keep,
            tc_in: "01:02:11:14",
            duration: "00:00:10:00",
            from_csv: true,
            status: ClipStatus::Processed,
            note: "",
        },
        FixtureClip {
            id: "c08",
            new_name: "02_017_01_02a",
            source_name: "A004C008_260112DJ",
            scene: "017",
            shot: "01",
            take: "02",
            camera: "a",
            rating: Rating::Ok,
            tc_in: "01:02:33:19",
            duration: "00:00:07:17",
            from_csv: true,
            status: ClipStatus::Processed,
            note: "",
        },
        FixtureClip {
            id: "c09",
            new_name: "02_017_02_01跑",
            source_name: "A004C009_260112DJ",
            scene: "017",
            shot: "02",
            take: "01跑",
            camera: "",
            rating: Rating::Ng,
            tc_in: "01:02:58:08",
            duration: "00:00:06:22",
            from_csv: true,
            status: ClipStatus::Processed,
            note: "中文镜次",
        },
        FixtureClip {
            id: "c10",
            new_name: "02_018_01_01a",
            source_name: "A005C010_260112DJ",
            scene: "018",
            shot: "01",
            take: "01",
            camera: "a",
            rating: Rating::Ok,
            tc_in: "01:03:21:11",
            duration: "00:00:15:06",
            from_csv: true,
            status: ClipStatus::Processed,
            note: "",
        },
        FixtureClip {
            id: "c11",
            new_name: "02_018_01_02b",
            source_name: "B002C011_260112DJ",
            scene: "018",
            shot: "01",
            take: "02",
            camera: "b",
            rating: Rating::Keep,
            tc_in: "01:03:44:16",
            duration: "00:00:12:19",
            from_csv: true,
            status: ClipStatus::Processed,
            note: "",
        },
        FixtureClip {
            id: "c12",
            new_name: "02_018_02_01a",
            source_name: "A005C012_260112DJ",
            scene: "018",
            shot: "02",
            take: "01",
            camera: "a",
            rating: Rating::Ok,
            tc_in: "01:04:09:02",
            duration: "00:00:13:10",
            from_csv: true,
            status: ClipStatus::Processed,
            note: "",
        },
        FixtureClip {
            id: "c13",
            new_name: "02_019_01_01a",
            source_name: "A006C013_260112DJ",
            scene: "019",
            shot: "01",
            take: "01",
            camera: "a",
            rating: Rating::Ok,
            tc_in: "01:04:37:21",
            duration: "00:00:09:14",
            from_csv: true,
            status: ClipStatus::Processed,
            note: "",
        },
        FixtureClip {
            id: "c14",
            new_name: "02_019_02_01a",
            source_name: "A006C014_260112DJ",
            scene: "019",
            shot: "02",
            take: "01",
            camera: "a",
            rating: Rating::None,
            tc_in: "01:05:01:07",
            duration: "00:00:11:03",
            from_csv: false,
            status: ClipStatus::Processed,
            note: "CSV 未匹配",
        },
        FixtureClip {
            id: "c15",
            new_name: "02_019_02_02b",
            source_name: "B003C015_260112DJ",
            scene: "019",
            shot: "02",
            take: "02",
            camera: "b",
            rating: Rating::Ok,
            tc_in: "01:05:26:13",
            duration: "00:00:16:20",
            from_csv: true,
            status: ClipStatus::Processed,
            note: "",
        },
        FixtureClip {
            id: "c16",
            new_name: "—",
            source_name: "ATMOS_WILD_01",
            scene: "—",
            shot: "—",
            take: "—",
            camera: "—",
            rating: Rating::None,
            tc_in: "01:05:58:00",
            duration: "00:00:30:00",
            from_csv: false,
            status: ClipStatus::Ignored,
            note: "纯音频 clip，保留节点不参与命名",
        },
        FixtureClip {
            id: "c17",
            new_name: "—",
            source_name: "ATMOS_WILD_02",
            scene: "—",
            shot: "—",
            take: "—",
            camera: "—",
            rating: Rating::None,
            tc_in: "01:06:31:12",
            duration: "00:00:24:08",
            from_csv: false,
            status: ClipStatus::Ignored,
            note: "纯音频 clip，保留节点不参与命名",
        },
        FixtureClip {
            id: "c18",
            new_name: "—",
            source_name: "SLATE_STILL_01.jpg",
            scene: "—",
            shot: "—",
            take: "—",
            camera: "—",
            rating: Rating::None,
            tc_in: "01:06:59:04",
            duration: "00:00:05:00",
            from_csv: false,
            status: ClipStatus::Ignored,
            note: "静帧无场记，节点保留",
        },
        FixtureClip {
            id: "c19",
            new_name: "02_020_01_01a",
            source_name: "A007C019_260112DJ",
            scene: "020",
            shot: "01",
            take: "01",
            camera: "a",
            rating: Rating::Ok,
            tc_in: "01:07:20:18",
            duration: "00:00:14:11",
            from_csv: true,
            status: ClipStatus::Skipped,
            note: "用户标记跳过",
        },
        FixtureClip {
            id: "c20",
            new_name: "02_020_01_02a",
            source_name: "A007C020_260112DJ",
            scene: "020",
            shot: "01",
            take: "02",
            camera: "a",
            rating: Rating::Ng,
            tc_in: "01:07:48:09",
            duration: "00:00:10:05",
            from_csv: true,
            status: ClipStatus::Skipped,
            note: "用户标记跳过",
        },
        FixtureClip {
            id: "c21",
            new_name: "—",
            source_name: "A008C021_260112DJ",
            scene: "021",
            shot: "03",
            take: "—",
            camera: "a",
            rating: Rating::None,
            tc_in: "01:08:15:22",
            duration: "00:00:09:02",
            from_csv: false,
            status: ClipStatus::Failed,
            note: "shottake 缺少镜次段",
        },
    ];

    let diagnostics = vec![
        Diagnostic {
            level: DiagnosticLevel::Warning,
            code: "CSV_UNMATCHED".into(),
            cause: "片段 A006C014_260112DJ 在 CSV 中无对应 Name".into(),
            object_id: Some("c14".into()),
            impact: "该片段按无 CSV 格式命名，不含 Episode 前缀".into(),
            blocks_export: false,
            suggested_action: Some("核对场记单是否缺少此镜".into()),
        },
        Diagnostic {
            level: DiagnosticLevel::Error,
            code: "SHOTTAKE_INVALID".into(),
            cause: "片段 A008C021_260112DJ 的 shottake 缺少镜次段".into(),
            object_id: Some("c21".into()),
            impact: "无法生成规范命名，片段保持原名".into(),
            blocks_export: true,
            suggested_action: Some("在场记单补齐 shot-take 后重新导入".into()),
        },
        Diagnostic {
            level: DiagnosticLevel::Info,
            code: "AUDIO_ONLY_IGNORED".into(),
            cause: "2 条纯音频 clip 不参与命名".into(),
            object_id: None,
            impact: "节点保留在 XML，计入 ignored".into(),
            blocks_export: false,
            suggested_action: None,
        },
        Diagnostic {
            level: DiagnosticLevel::Info,
            code: "STILL_FRAME_IGNORED".into(),
            cause: "1 条无场记的 .jpg 静帧不参与命名".into(),
            object_id: None,
            impact: "节点保留在 XML，计入 ignored".into(),
            blocks_export: false,
            suggested_action: None,
        },
        Diagnostic {
            level: DiagnosticLevel::Warning,
            code: "RATING_MISSING".into(),
            cause: "片段 B001C005_260112DJ 无评分记录".into(),
            object_id: Some("c05".into()),
            impact: "命名不含评分后缀".into(),
            blocks_export: false,
            suggested_action: Some("确认场记单评分列".into()),
        },
        Diagnostic {
            level: DiagnosticLevel::Info,
            code: "RESOLUTION_NORMALIZED".into(),
            cause: "文档级分辨率已统一为 3840×2160".into(),
            object_id: None,
            impact: "所有序列使用统一帧尺寸".into(),
            blocks_export: false,
            suggested_action: None,
        },
    ];

    let revisions = vec![
        RevisionEntry {
            revision: 6,
            operation: "operation.apply",
            committed_at: "2026-08-15 21:42",
            summary: "写回 15 条命名与标签",
        },
        RevisionEntry {
            revision: 5,
            operation: "operation.preview",
            committed_at: "2026-08-15 21:38",
            summary: "预演通过：15 命名 / 3 忽略 / 2 跳过 / 1 失败",
        },
        RevisionEntry {
            revision: 4,
            operation: "import.csv",
            committed_at: "2026-08-15 21:31",
            summary: "匹配场记单 20 行，1 行未匹配",
        },
        RevisionEntry {
            revision: 3,
            operation: "import.xml",
            committed_at: "2026-08-15 21:26",
            summary: "解析序列 21 条 clip",
        },
        RevisionEntry {
            revision: 2,
            operation: "project.open",
            committed_at: "2026-08-15 21:20",
            summary: "打开既有项目（幂等）",
        },
        RevisionEntry {
            revision: 1,
            operation: "project.create",
            committed_at: "2026-08-15 21:02",
            summary: "创建 .doublelove 项目",
        },
    ];

    FixtureSet {
        project_name: "青空日记 · 第 2 集",
        episode_label: "E02",
        clips,
        diagnostics,
        revisions,
        counts: OperationCounts {
            total: 21,
            processed: 15,
            skipped: 2,
            failed: 1,
            unmatched: 0,
        },
        csv_unmatched: 1,
        export_blocked: true,
    }
}
