// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostRequest = { v: number, id: string, } & ({ "method": "handshake", client: string, client_protocol: number, } | { "method": "health" } | { "method": "shutdown" });
