// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostProtocolError } from "./HostProtocolError";
import type { HostResult } from "./HostResult";

export type HostResponse = { v: number, id: string, } & ({ "status": "ok", result: HostResult, } | { "status": "error", error: HostProtocolError, });
