// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostHello } from "./HostHello";

export type HostResult = { "type": "hello", "data": HostHello } | { "type": "health", "data": { healthy: boolean, } } | { "type": "shutdown" } | { "type": "invoke", "data": unknown };
