// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostHello = { protocol: number, host_version: string, engine_version: string, capabilities: Array<string>, };
