// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 媒体资产状态机：imported → prepared → transcribed。
 */
export type AssetStatus = "imported" | "prepared" | "transcribed";
