// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasFit } from "./CanvasFit";

/**
 * 项目级画布。时间仍使用帧/采样整数；视觉参数只用于预览与渲染。
 */
export type CanvasSpec = { width: bigint, height: bigint, background: string, fit: CanvasFit, position_x: number, position_y: number, scale: number, rotation_degrees: number, opacity: number, };
