// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 某个导出目标对本次时间线的明确保留与有损边界；不把“可以导入”伪装成“视觉完全一致”。
 */
export type CompatibilityReport = { target: string, preserved: Array<string>, limitations: Array<string>, };
