// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticLevel } from "./DiagnosticLevel";

export type Diagnostic = { level: DiagnosticLevel, code: string, cause: string, object_id: string | null, impact: string, blocks_export: boolean, suggested_action: string | null, };
