// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoctorCapabilityStatus } from "./DoctorCapabilityStatus";

export type DoctorCapabilityCheck = { id: string, status: DoctorCapabilityStatus, detail: string, suggested_action: string | null, };
