// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoctorModelCheck } from "./DoctorModelCheck";

/**
 * 本地诊断报告。路径字段仅用根目录标签，不携带绝对路径。
 */
export type DoctorReport = { schema_version: number, generated_at: string, architecture: string, os_version: string, memory_bytes: bigint, free_model_bytes: bigint, model_root_available: boolean, ffmpeg_available: boolean, libass_available: boolean, asr_runtime_ready: boolean, speaker_runtime_ready: boolean, model_checks: Array<DoctorModelCheck>, warnings: Array<string>, };
