// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelInstallState } from "./ModelInstallState";

/**
 * 诊断中的单项模型完整性结果。
 */
export type DoctorModelCheck = { model_id: string, state: ModelInstallState, revision: string, integrity_ok: boolean, error_code: string | null, };
