// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 诊断中的运行时能力结果。`detail` 和建议不得包含绝对路径或用户媒体内容。
 */
export type DoctorCapabilityStatus = "ready" | "warning" | "blocked" | "not_run";
