// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 编辑操作类型。切片只实现 Omit/Restore；Move/Trim 为 PRD 契约占位。
 */
export type EditType = "omit" | "restore" | "move" | "trim";
