// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 编辑行为。切片只实现 RippleAv（连带音视频联动）。
 */
export type EditBehavior = "text_only" | "subtitle_only" | "ripple_av";
