// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineIR } from "./TimelineIR";

/**
 * 导出结果：IR 必有（preview 也返回）；文件与 sha256 仅 apply 后有。
 */
export type ExportOutcome = { ir: TimelineIR, artifact_path: string | null, sha256: string | null, };
