// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TimelineIR 中的一个片段：源素材的连续帧区间 → 输出时间线的连续帧区间。
 * 帧区间均为 [in, out) 半开。
 */
export type IrClip = { clip_index: bigint, source_in_frame: bigint, source_out_frame: bigint, timeline_start_frame: bigint, timeline_end_frame: bigint, first_word_ordinal: bigint, last_word_ordinal: bigint, };
