// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一个旧模型清理候选。路径故意不出现在该类型中；设置页只需要名称、状态和
 * 可释放空间，实际删除始终由受管模型根中的 `ModelManager` 执行。
 */
export type LegacyModelCleanupItem = { model_id: string, display_name: string, bytes_to_free: bigint, reason: string | null, };
