// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyModelCleanupItem } from "./LegacyModelCleanupItem";

/**
 * 当前 MLX 模型安装后可安全清理的旧版本预览。
 */
export type LegacyModelCleanupPreview = { target_model_id: string, bytes_to_free: bigint, removable: Array<LegacyModelCleanupItem>, retained: Array<LegacyModelCleanupItem>, };
