// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 主轨的一条用户编辑记录，`source_*` 永远处于该源自身的帧率域。
 */
export type MainTrackClip = { id: string, source_asset_id: string, source_in_frame: bigint, source_out_frame: bigint, order_index: bigint, };
