// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output Time Map 的一段：源采样区间 ↔ 输出帧区间的线性映射。
 * SRT/XML/FCPXML/MD 未来只能从这同一份 Map 生成（PRD 不变量）。
 */
export type MapSegment = { src_start_sample: bigint, src_end_sample: bigint, out_start_frame: bigint, out_end_frame: bigint, };
