// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一个模型对另一个模型的安装依赖。
 */
export type ModelDependency = { model_id: string, required: boolean, reason: string, };
