// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelComponent } from "./ModelComponent";
import type { ModelDependency } from "./ModelDependency";
import type { ModelFile } from "./ModelFile";

/**
 * 内置模型清单中的模型描述。
 */
export type ModelDescriptor = { id: string, display_name: string, component: ModelComponent, repo_id: string | null, revision: string, files: Array<ModelFile>, license: string, license_url: string, dependencies: Array<ModelDependency>, min_memory_bytes: bigint | null, source_url_template: string, bundled: boolean, };
