// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelDescriptor } from "./ModelDescriptor";
import type { ModelInstallation } from "./ModelInstallation";

/**
 * 设置窗口用的目录快照。
 */
export type ModelDescriptorWithInstallation = { descriptor: ModelDescriptor, installation: ModelInstallation, };
