// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单个可验证归档的下载说明。归档本身和解压后的每个运行时文件都必须通过哈希校验。
 */
export type ModelArchive = { url: string, size_bytes: bigint, sha256: string, strip_prefix: string | null, };
