// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 内置模型的固定下载来源。旧清单默认视为 Hugging Face，以保持状态文件兼容；
 * 归档模型使用 `Official`，并仍须固定 SHA-256。
 */
export type ModelDownloadSource = "modelscope" | "huggingface" | "bundled" | "official";
