// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelArchive } from "./ModelArchive";
import type { ModelComponent } from "./ModelComponent";
import type { ModelDependency } from "./ModelDependency";
import type { ModelDownloadSource } from "./ModelDownloadSource";
import type { ModelFile } from "./ModelFile";
import type { ModelUiRole } from "./ModelUiRole";

/**
 * 内置模型清单中的模型描述。
 */
export type ModelDescriptor = { id: string, display_name: string, component: ModelComponent, ui_role: ModelUiRole, repo_id: string | null, download_source: ModelDownloadSource, revision: string, files: Array<ModelFile>, license: string, license_url: string, dependencies: Array<ModelDependency>, min_memory_bytes: bigint | null, source_url_template: string, replaces_model_id: string | null, archive: ModelArchive | null, bundled: boolean, };
