// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 安装器对外暴露的固定状态机。
 */
export type ModelInstallState = "not_installed" | "queued" | "downloading" | "paused" | "verifying" | "installed" | "corrupt" | "failed";
