// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 模型文件的固定完整性元数据。
 */
export type ModelFile = { path: string, size_bytes: bigint, sha256: string, allowed: boolean, };
