// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelInstallState } from "./ModelInstallState";

/**
 * 下载进度事件。绝不包含本地绝对路径。
 */
export type ModelDownloadProgress = { model_id: string, state: ModelInstallState, current_file: string | null, bytes_downloaded: bigint, bytes_total: bigint, file_bytes_downloaded: bigint, file_bytes_total: bigint, speed_bytes_per_second: bigint | null, };
