// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 模型在设置页中的呈现层级。依赖、随应用组件和旧权重仍保留给运行时与诊断，
 * 但不会伪装成用户可单独管理的主模型。
 */
export type ModelUiRole = "primary" | "dependency" | "bundled" | "legacy";
