// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 清单中的实际模型组件。
 */
export type ModelComponent = "asr" | "forced_aligner" | "vad" | "speaker";
