// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelQueueEntry } from "./ModelQueueEntry";

export type ModelQueueSnapshot = { active_model_id: string | null, entries: Array<ModelQueueEntry>, };
