// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelInstallState } from "./ModelInstallState";

/**
 * 可持久化的一条安装快照。路径故意只保存 staging id，不保存绝对目录。
 */
export type ModelInstallation = { model_id: string, revision: string, state: ModelInstallState, bytes_downloaded: bigint, bytes_total: bigint, staging_id: string | null, last_error_code: string | null, last_error_message: string | null, updated_at: string, };
