// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelQueueState } from "./ModelQueueState";

export type ModelQueueEntry = { model_id: string, position: number, state: ModelQueueState, };
