// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagnostic } from "./Diagnostic";
import type { OperationCounts } from "./OperationCounts";
import type { OperationStatus } from "./OperationStatus";
import type { OutputArtifact } from "./OutputArtifact";

export type OperationResult<T> = { status: OperationStatus, revision: bigint | null, data: T | null, counts: OperationCounts, diagnostics: Array<Diagnostic>, outputs: Array<OutputArtifact>, };
