// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 多源 Output Time Map。字幕、播放和 NLE 导出必须消费同一组段。
 */
export type OutputMapSegment = { source_asset_id: string, clip_id: string, src_start_sample: bigint, src_end_sample: bigint, out_start_frame: bigint, out_end_frame: bigint, };
