// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProgressEvent = { task: string, phase: string, completed: bigint | null, total: bigint | null, message: string, };
