// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompatibilityReport } from "./CompatibilityReport";
import type { SubtitleCue } from "./SubtitleCue";
import type { TimelineIRv2 } from "./TimelineIRv2";

/**
 * 所有项目级导出共享的只读预览。Apply 只把它写成目标格式，禁止重新编译时间线。
 */
export type ProjectExportPreview = { timeline: TimelineIRv2, subtitle_cues: Array<SubtitleCue>, compatibility: Array<CompatibilityReport>, };
