// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 有理数（构造即约分，分母恒正）。禁止从 f64 构造。
 */
export type Rational = { num: bigint, den: bigint, };
