// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * v2 编译后的主轨片段。输出帧一律属于项目输出帧率域。
 */
export type ResolvedTimelineClip = { id: string, source_asset_id: string, source_in_frame: bigint, source_out_frame: bigint, timeline_start_frame: bigint, timeline_end_frame: bigint, };
