// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 可审阅的项目历史条目。历史恢复本身也会生成一条新的 revision。
 */
export type RevisionHistoryEntry = { revision: bigint, operation: string, committed_at: string, restorable: boolean, };
