// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 源素材时间域内由文字删减得到的可恢复保留区间。它不改变原始媒体，只作为主轨
 * 编译前的 SourceCut 层；用户的 omit/restore 记录仍保存在项目历史中。
 */
export type SourceCut = { source_asset_id: string, source_in_frame: bigint, source_out_frame: bigint, first_word_ordinal: bigint, last_word_ordinal: bigint, };
