// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 某个词的说话人归属。声纹与原始音频不进入该 DTO。
 */
export type SpeakerAssignment = { speaker_id: string, confidence: number | null, evidence: string, };
