// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 用户主动请求 Agent 前展示的最小数据包。没有音频、声纹、路径或其他说话人的全文。
 */
export type SpeakerNameAgentPayload = { speaker_id: string, utterances: Array<string>, instruction: string, };
