// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpeakerIdentity } from "./SpeakerIdentity";
import type { SpeakerMergeProposal } from "./SpeakerMergeProposal";

/**
 * 一次本地说话人分离完成后的可展示摘要。声纹向量故意不出现在这个契约中。
 */
export type SpeakerDiarizationResult = { asset_id: string, segment_count: bigint, speakers: Array<SpeakerIdentity>, merge_proposals: Array<SpeakerMergeProposal>, };
