// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 项目内可见的说话人身份。自动候选与人工确认都只改这层映射。
 */
export type SpeakerIdentity = { id: string, display_name: string, aliases: Array<string>, color: string, confirmed: boolean, };
