// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 名称候选只是一条可审阅建议，绝不自动改写身份显示名。
 */
export type SpeakerNameProposal = { speaker_id: string, candidate_name: string, quote: string, confidence: number, source: string, reason: string, };
