// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 跨素材合并候选，永远由用户确认后才会改变 SpeakerIdentity。
 */
export type SpeakerMergeProposal = { id: string, left_speaker_id: string, right_speaker_id: string, similarity: number, evidence: string, status: string, };
