// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 某个源素材中由匿名/已确认说话人覆盖的声学区间。
 */
export type SpeakerSegment = { id: string, asset_id: string, speaker_id: string, start_sample: bigint, end_sample: bigint, confidence: number | null, };
