// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 输出时间域内的一条字幕 Cue。
 */
export type SubtitleCue = { id: string, source_word_ids: Array<string>, speaker_id: string | null, speaker_name: string | null, start_frame: bigint, end_frame: bigint, text: string, };
