// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasSpec } from "./CanvasSpec";
import type { FrameRate } from "./FrameRate";
import type { OutputMapSegment } from "./OutputMapSegment";
import type { ResolvedTimelineClip } from "./ResolvedTimelineClip";
import type { SourceCut } from "./SourceCut";
import type { TimelineSource } from "./TimelineSource";

/**
 * 多素材主轨的唯一输出中间表示。
 */
export type TimelineIRv2 = { schema_version: number, name: string, rate: FrameRate, canvas: CanvasSpec, sources: Array<TimelineSource>, source_cuts: Array<SourceCut>, clips: Array<ResolvedTimelineClip>, output_duration_frames: bigint, output_map: Array<OutputMapSegment>, };
