// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameRate } from "./FrameRate";

/**
 * 多素材时间线中的源媒体事实。所有路径均为只读引用。
 */
export type TimelineSource = { asset_id: string, display_name: string, original_path: string, rate: FrameRate, source_duration_frames: bigint, audio_sample_rate: bigint, audio_channels: bigint | null, width: bigint | null, height: bigint | null, source_tc_start_frame: bigint | null, source_tc_is_drop_frame: boolean, };
