// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameRate } from "./FrameRate";
import type { IrClip } from "./IrClip";
import type { MapSegment } from "./MapSegment";

/**
 * 时间线中间表示：编译器产物、导出器唯一输入。
 * Exporter 禁止重算剪辑时间，只做 IR → 目标格式映射（PRD 不变量）。
 */
export type TimelineIR = { schema_version: number, name: string, rate: FrameRate, source_asset_id: string, source_duration_frames: bigint, output_duration_frames: bigint, clips: Array<IrClip>, output_map: Array<MapSegment>, };
