// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditOperation } from "./EditOperation";
import type { TranscriptSegment } from "./TranscriptSegment";
import type { WordAnchor } from "./WordAnchor";

/**
 * TranscriptView 一次渲染所需的全部数据（segment.rs::transcript_view 装配）。
 */
export type TranscriptViewData = { words: Array<WordAnchor>, segments: Array<TranscriptSegment>, 
/**
 * 当前活跃的 omit 操作（恢复操作的入口）。
 */
omits: Array<EditOperation>, };
