// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 词锚点：转录产物的最小剪辑单元（PRD 不变量）。
 * `start_sample`/`end_sample` 以资产音频采样率为时基的采样级整数。
 */
export type WordAnchor = { word_id: string, asset_id: string, 
/**
 * 资产内词序，从 0 开始连续递增；UNIQUE(asset_id, ordinal)。
 */
ordinal: bigint, raw_text: string, display_text: string, language: string | null, start_sample: bigint, end_sample: bigint, confidence: number | null, 
/**
 * 合成词（纠错/对齐产物）不得驱动剪切；切片只产生 false。
 */
synthetic: boolean, 
/**
 * 合成词溯源；非合成词恒为 None。
 */
source_word_ids: Array<string> | null, };
