// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpeakerAssignment } from "./SpeakerAssignment";

/**
 * 词锚点：转录产物的最小剪辑单元（PRD 不变量）。
 * `start_sample`/`end_sample` 以资产音频采样率为时基的采样级整数。
 */
export type WordAnchor = { word_id: string, asset_id: string, ordinal: bigint, raw_text: string, display_text: string, language: string | null, start_sample: bigint, end_sample: bigint, confidence: number | null, synthetic: boolean, source_word_ids: Array<string> | null, speaker_assignments: Array<SpeakerAssignment>, };
